name: CI

on:
  pull_request:
    types: [labeled, synchronize, unlocked, opened]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Dump stuff
        run: |
          echo ${{ github.event.pull_request.labels[0].name }}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
          
      - name: Create branch and force push
        run: |
          pr_labels=${{ toJson(github.event.pull_request.labels) }}
          label_name="qa-1"

          if echo "$pr_labels" | jq -r '.[].name' | grep -q "$label_name"; then
            echo "PR labeled with 'qa-1'. Running QA checks..."
            git config user.name github-actions
            git config user.email github-actions@github.com
            git checkout -b internal/qa1-${{ github.event.number }}-${GITHUB_HEAD_REF}
            git push -f --set-upstream origin internal/qa1-${{ github.event.number }}-${GITHUB_HEAD_REF}
          else
            echo "PR not labeled with 'qa-1'. No action needed."
          fi
